FROM ghcr.io/maxking/mailman-ci-runner:latest

WORKDIR /work

USER root
COPY repo.bundle /tmp/repo.bundle
RUN git clone /tmp/repo.bundle /work
RUN git -C /work config --global --add safe.directory /work
RUN git 
RUN git rebase --onto "master" "windows-rename" "windows-master" || (echo "Rebase failed"; exit 1)
RUN tox -e py312-nocov
